cc_binary(
    name = 'hello_world',
    srcs = [
        'hello_world.cpp',
    ],
    deps = [
        '//AF:AF',
        '#pthread'
    ],
    defs = [
        '_GLIBCXX_USE_NANOSLEEP',
        '_GLIBCXX_USE_SCHED_YIELD'
    ],
    extra_cppflags = [
        '-fPIC',
        '-std=c++11',
    ]
)

cc_binary(
    name = 'alignment',
    srcs = [
        'alignment.cpp',
    ],
    deps = [
        '//AF:AF',
        '#pthread'
    ],
    defs = [
        '_GLIBCXX_USE_NANOSLEEP',
        '_GLIBCXX_USE_SCHED_YIELD'
    ],
    extra_cppflags = [
        '-fPIC',
        '-std=c++11',
    ]
)

cc_binary(
    name = 'custom_allocators',
    srcs = [
        'custom_allocators.cpp',
    ],
    deps = [
        '//AF:AF',
        '#pthread'
    ],
    defs = [
        '_GLIBCXX_USE_NANOSLEEP',
        '_GLIBCXX_USE_SCHED_YIELD'
    ],
    extra_cppflags = [
        '-fPIC',
        '-std=c++11',
    ]
)

cc_binary(
    name = 'file_reader',
    srcs = [
        'file_reader.cpp',
    ],
    deps = [
        '//AF:AF',
        '#pthread'
    ],
    defs = [
        '_GLIBCXX_USE_NANOSLEEP',
        '_GLIBCXX_USE_SCHED_YIELD'
    ],
    extra_cppflags = [
        '-fPIC',
        '-std=c++11',
    ]
)

cc_binary(
    name = 'message_registration',
    srcs = [
        'message_registration.cpp',
    ],
    deps = [
        '//AF:AF',
        '#pthread'
    ],
    defs = [
        '_GLIBCXX_USE_NANOSLEEP',
        '_GLIBCXX_USE_SCHED_YIELD'
    ],
    extra_cppflags = [
        '-fPIC',
        '-std=c++11',
    ]
)

cc_binary(
    name = 'unhandled_messages',
    srcs = [
        'unhandled_messages.cpp',
    ],
    deps = [
        '//AF:AF',
        '#pthread'
    ],
    defs = [
        '_GLIBCXX_USE_NANOSLEEP',
        '_GLIBCXX_USE_SCHED_YIELD'
    ],
    extra_cppflags = [
        '-fPIC',
        '-std=c++11',
    ]
)

cc_binary(
    name = 'ping_pong',
    srcs = [
        'ping_pong.cpp',
    ],
    deps = [
        '//AF:AF',
        '#pthread'
    ],
    defs = [
        '_GLIBCXX_USE_NANOSLEEP',
        '_GLIBCXX_USE_SCHED_YIELD'
    ],
    extra_cppflags = [
        '-fPIC',
        '-std=c++11',
    ]
)

